[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
auth = { path = "../auth" }
domain = { path = "../domain/" }
serde_json = "^1.0"
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "2.0.3", features = ["postgres", "r2d2"] }
dotenv = "0.15"
