[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
env_logger = "0.10.0"
serde_json = "^1.0"
serde = { version = "1.0", features = ["derive"] }
application = { path = "../application/" }
domain = { path = "../domain/" }
context = { path = "../context/" }
